- hosts: all
  become: yes
  become_user: root
  vars:
    ansible_python_interpreter: /usr/bin/python3
    
  tasks:
    - name: Installing {{ package_name }}
      package:
         name:
          - "{{ package_name }}"
